#packages:
#  bms0:
#    url: https://github.com/sergeysaley/ESPHome-packages
#    files:
#      - path: packages/bms/seplos.yaml
#        vars:
#          mac_address: "60:6E:41:1D:C7:67"
#          prefix: "bms0"
#          interval: 30
#    ref: main
#    refresh: 0s
#
# mac_address
# prefix
# interval
ble_client:
  - mac_address: ${mac_address}
    id: ${prefix}_client

seplos_bms_ble:
  - ble_client_id: ${prefix}_client
    id: ${prefix}
    update_interval: ${interval}s

text_sensor:
  - platform: seplos_bms_ble
    seplos_bms_ble_id: ${prefix}
    software_version:
      name: "${prefix} software version"
    device_model:
      name: "${prefix} device model"
    hardware_version:
      name: "${prefix} hardware version"
    alarms:
      name: "${prefix} alarms"
      
sensor:
  - platform: seplos_bms_ble
    seplos_bms_ble_id: ${prefix}
    alarm_event1_bitmask:
      name: "${prefix} alarm event 1 bitmask"
      on_value:
        then:
          - script.execute: ble_activity_blink
    alarm_event2_bitmask:
      name: "${prefix} alarm event 2 bitmask"
    alarm_event3_bitmask:
      name: "${prefix} alarm event 3 bitmask"
    alarm_event4_bitmask:
      name: "${prefix} alarm event 4 bitmask"
    alarm_event5_bitmask:
      name: "${prefix} alarm event 5 bitmask"
    alarm_event6_bitmask:
      name: "${prefix} alarm event 6 bitmask"
    alarm_event7_bitmask:
      name: "${prefix} alarm event 7 bitmask"
    alarm_event8_bitmask:
      name: "${prefix} alarm event 8 bitmask"
    total_voltage:
      name: "${prefix} total voltage"
    current:
      name: "${prefix} current"
    charging_power:
      name: "${prefix} charging power"
    discharging_power:
      name: "${prefix} discharging power"
    capacity_remaining:
      name: "${prefix} capacity remaining"
    state_of_charge:
      name: "${prefix} state of charge"
    nominal_capacity:
      name: "${prefix} nominal capacity"
    charging_cycles:
      name: "${prefix} charging cycles"
    min_cell_voltage:
      name: "${prefix} min cell voltage"
    max_cell_voltage:
      name: "${prefix} max cell voltage"
    min_voltage_cell:
      name: "${prefix} min voltage cell"
    max_voltage_cell:
      name: "${prefix} max voltage cell"
    delta_cell_voltage:
      name: "${prefix} delta cell voltage"
    average_cell_voltage:
      name: "${prefix} average cell voltage"
    average_cell_temperature:
      name: "${prefix} average cell temperature"
    ambient_temperature:
      name: "${prefix} ambient temperature"
    mosfet_temperature:
      name: "${prefix} mosfet temperature"
    state_of_health:
      name: "${prefix} state of health"
    port_voltage:
      name: "${prefix} port voltage"
    battery_capacity:
      name: "${prefix} battery capacity"
    temperature_1:
      name: "${prefix} temperature 1"
    temperature_2:
      name: "${prefix} temperature 2"
    temperature_3:
      name: "${prefix} temperature 3"
    temperature_4:
      name: "${prefix} temperature 4"
    cell_voltage_1:
      name: "${prefix} cell voltage 1"
    cell_voltage_2:
      name: "${prefix} cell voltage 2"
    cell_voltage_3:
      name: "${prefix} cell voltage 3"
    cell_voltage_4:
      name: "${prefix} cell voltage 4"
    cell_voltage_5:
      name: "${prefix} cell voltage 5"
    cell_voltage_6:
      name: "${prefix} cell voltage 6"
    cell_voltage_7:
      name: "${prefix} cell voltage 7"
    cell_voltage_8:
      name: "${prefix} cell voltage 8"
    cell_voltage_9:
      name: "${prefix} cell voltage 9"
    cell_voltage_10:
      name: "${prefix} cell voltage 10"
    cell_voltage_11:
      name: "${prefix} cell voltage 11"
    cell_voltage_12:
      name: "${prefix} cell voltage 12"
    cell_voltage_13:
      name: "${prefix} cell voltage 13"
    cell_voltage_14:
      name: "${prefix} cell voltage 14"
    cell_voltage_15:
      name: "${prefix} cell voltage 15"
    cell_voltage_16:
      name: "${prefix} cell voltage 16"
