esphome:
  name: ${device_name}
  comment: ${device_location}
  name_add_mac_suffix: false

# Enable logging
logger:

# Enable Home Assistant API
#wifi:
#  networks:
#    - ssid: !secret wifi_ssid
#      password: !secret wifi_password
#  ap:
#    ssid: ${device_name}
#    password: !secret ap_password
wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password
  platform: esphome

web_server:
  port: 80
  version: 3

text_sensor:
  - <<: !include ip_address.yaml
  - <<: !include location.yaml    
  - <<: !include version.yaml

binary_sensor:
  - <<: !include status.yaml

sensor:
  - <<: !include wifi_signal.yaml

switch:
  - platform: restart
    name: "${device_name} restart"  
