esphome:
  name: ${device_name}
  comment: ${device_location}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password
  platform: esphome

web_server:
  port: 80
  version: 3

text_sensor:
  - <<: !include common/text_sensor/ip_address.yaml
  - <<: !include common/text_sensor/location.yaml    
  - <<: !include common/text_sensor/version.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/wifi_signal.yaml

switch:
  - platform: restart
    name: "${device_name} restart"  
