binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    id: button_1
    on_press:
      then:
        - light.toggle: light_1

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "${device_name} Light_1"
    id: light_1
    output: relay_1    

status_led:
  pin:
    number: GPIO13
    inverted: no
