esphome:
#  on_boot:
#    then:
#      - light.turn_on: 
#          id: led
#          brightness: 100%
#          effect: "Flicker Effect"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    id: button_1
    on_press:
      then:
        - light.toggle: light_1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    id: button_2
    on_press:
      then:
        - light.toggle: light_2
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
    id: button_3
    on_press:
      then:
        - light.toggle: light_3

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: esp8266_pwm
    pin: GPIO13
    inverted: True
    id: blue_led
    
light:
  - platform: binary
    name: "Light_1"
    id: light_1
    output: relay_1
  - platform: binary
    name: "Light_2"
    id: light_2
    output: relay_2
  - platform: binary
    name: "Light_3"
    id: light_3
    output: relay_3
  - platform: monochromatic
    name: "LED"
    disabled_by_default: true
    id: led
    output: blue_led
    default_transition_length: 500ms
    effects:
      - flicker:
          name: "Flicker Effect"
          alpha: 70%
          intensity: 25%
