external_components:
  - source: github://Averyy/esphome-custom-components
    refresh: 0s

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  frequency: 400kHz

vl53l1x:
  distance_mode: long
  update_interval: 0.5s

sensor:
  - platform: vl53l1x
    i2c_id: bus_a
    distance:
      name: "VL53L1X ToF Distance Sensor"
      id: water_sensor
      entity_category: "diagnostic"
      filters:
        - lambda: |-
            static auto start_time = millis();
            if (millis() - start_time < 120000) { // 2 minutes
              return {}; // Return empty to skip this reading
            }
            // After 2 minutes, apply your existing filters
            if (x < 45 || x > 4200 || x == 0.0 || std::isnan(x)) {
              return 0;
            }
            return x;
        - quantile:
            window_size: 11
            send_every: 11
            send_first_at: 11
            quantile: 0.5
