external_components:
  - source: github://soldierkam/vl53l1x_sensor
    refresh: 0s

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  frequency: 400kHz

sensor:
  - platform: vl53l1x_sensor
    name: Distance    
    distance_mode: MEDIUM
    signal_threshold: 512
    timing_budget: 200ms
    update_interval: 15s
    accuracy_decimals: 3
    roi_center: 199
    roi_size:
      x: 15
      y: 15
    ambient_rate_sensor: 
      name: "Ambient Rate [MCPS]"
    avg_signal_rate_sensor: 
      name: "Average Signal Rate [MCPS]"
    peak_signal_rate_sensor: 
      name: "Peak Signal Rate [MCPS]"
    range_status_sensor:
      name: "Range Status"
