esphome:
  name: ${device_name}
  comment: ${device_location}
  on_boot:
    priority: 200
    then:
      - light.turn_on: 
          id: led
          brightness: 50%
          effect: "Flicker Effect"

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "switch_1"
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "switch_2"
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "switch_3"
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: "switch_4"

switch:
  - platform: output
    name: "${device_name} Switch_1"
    id: switch_1
    output: relay_1
  - platform: output
    name: "${device_name} Switch_2"
    id: switch_2
    output: relay_2
  - platform: output
    name: "${device_name} Switch_3"
    id: switch_3
    output: relay_3
  - platform: output
    name: "${device_name} Switch_4"
    id: switch_4
    output: relay_4

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    id: led
    name: "${device_name} Bluelight"
    output: blue_led
    effects:
      - flicker:
          name: "Flicker Effect"
          alpha: 75%
          intensity: 25%
     
time:
  - platform: sntp
    id: my_time
