
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    id: button_1
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: output
    name: "Switch_1"
    id: switch_1
    output: relay_1
    on_turn_on:
      then:
        - delay: 0.5s
        - switch.turn_off: switch_1

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes
